//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Screen_Recorder.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stringsxxx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringsxxx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Screen_Recorder.Langs.Stringsxxx", typeof(Stringsxxx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于本软件.
        /// </summary>
        public static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择计算机音频.
        /// </summary>
        public static string BtnDeskAudio {
            get {
                return ResourceManager.GetString("BtnDeskAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择计算机音频.
        /// </summary>
        public static string BtnDeskAudio2 {
            get {
                return ResourceManager.GetString("BtnDeskAudio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出软件.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混合音频和视频文件.
        /// </summary>
        public static string BtnMergeAll {
            get {
                return ResourceManager.GetString("BtnMergeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混合音频和视频文件.
        /// </summary>
        public static string BtnMergeAll2 {
            get {
                return ResourceManager.GetString("BtnMergeAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择麦克风音频.
        /// </summary>
        public static string BtnMicAudio {
            get {
                return ResourceManager.GetString("BtnMicAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件夹.
        /// </summary>
        public static string btnOutputF {
            get {
                return ResourceManager.GetString("btnOutputF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件夹.
        /// </summary>
        public static string btnOutputF2 {
            get {
                return ResourceManager.GetString("btnOutputF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始录音.
        /// </summary>
        public static string btnStartRecording {
            get {
                return ResourceManager.GetString("btnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止录影.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个视频.
        /// </summary>
        public static string BtnVideo {
            get {
                return ResourceManager.GetString("BtnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个视频.
        /// </summary>
        public static string BtnVideo2 {
            get {
                return ResourceManager.GetString("BtnVideo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制措施.
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显微镜.
        /// </summary>
        public static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算机音频（扬声器或耳机）.
        /// </summary>
        public static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音频设置.
        /// </summary>
        public static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音频器件.
        /// </summary>
        public static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string languagesToolStripMenuItem {
            get {
                return ResourceManager.GetString("languagesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只混合计算机音频和视频.
        /// </summary>
        public static string mergeVideoAndDesktopAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoAndDesktopAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混合所有媒体文件.
        /// </summary>
        public static string mergeVideoDesktopAndMicAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoDesktopAndMicAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你必须先按下录音按钮。.
        /// </summary>
        public static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅计算机音频.
        /// </summary>
        public static string RadioDesktop {
            get {
                return ResourceManager.GetString("RadioDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算机音频和麦克风.
        /// </summary>
        public static string RadioTwoTrack {
            get {
                return ResourceManager.GetString("RadioTwoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混合音频和视频文件.
        /// </summary>
        public static string remuxToolStripMenuItem {
            get {
                return ResourceManager.GetString("remuxToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只混合计算机视频和音频.
        /// </summary>
        public static string titleMerge1 {
            get {
                return ResourceManager.GetString("titleMerge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混合所有文件.
        /// </summary>
        public static string titleMerge2 {
            get {
                return ResourceManager.GetString("titleMerge2", resourceCulture);
            }
        }
    }
}
