//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Screen_Recorder.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Screen_Recorder.Langs.Strings", typeof(StringsEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Recording.
        /// </summary>
        internal static string btnStartRecording {
            get {
                return ResourceManager.GetString("btnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        internal static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System sounds (speaker).
        /// </summary>
        internal static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio settings.
        /// </summary>
        internal static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound devices.
        /// </summary>
        internal static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languagesToolStripMenuItem {
            get {
                return ResourceManager.GetString("languagesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge video and system sounds.
        /// </summary>
        internal static string mergeVideoAndDesktopAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoAndDesktopAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge all media.
        /// </summary>
        internal static string mergeVideoDesktopAndMicAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoDesktopAndMicAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not recording anything.
        /// </summary>
        internal static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System sounds.
        /// </summary>
        internal static string RadioDesktop {
            get {
                return ResourceManager.GetString("RadioDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System sounds and microphone audio.
        /// </summary>
        internal static string RadioTwoTrack {
            get {
                return ResourceManager.GetString("RadioTwoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge media files.
        /// </summary>
        internal static string remuxToolStripMenuItem {
            get {
                return ResourceManager.GetString("remuxToolStripMenuItem", resourceCulture);
            }
        }

        internal static string BtnVideo
        {
            get
            {
                return ResourceManager.GetString("BtnVideo", resourceCulture);
            }
        }

        internal static string BtnDeskAudio
        {
            get
            {
                return ResourceManager.GetString("BtnDeskAudio", resourceCulture);
            }
        }

        internal static string BtnMergeAll
        {
            get
            {
                return ResourceManager.GetString("BtnMergeAll", resourceCulture);
            }
        }

        internal static string btnOutputF
        {
            get
            {
                return ResourceManager.GetString("btnOutputF", resourceCulture);
            }
        }

        internal static string titleMerge1
        {
            get
            {
                return ResourceManager.GetString("titleMerge1", resourceCulture);
            }
        }

        internal static string titleMerge2
        {
            get
            {
                return ResourceManager.GetString("titleMerge2", resourceCulture);
            }
        }

        internal static string BtnVideo2
        {
            get
            {
                return ResourceManager.GetString("BtnVideo2", resourceCulture);
            }
        }

        internal static string BtnDeskAudio2
        {
            get
            {
                return ResourceManager.GetString("BtnDeskAudio2", resourceCulture);
            }
        }

        internal static string BtnMergeAll2
        {
            get
            {
                return ResourceManager.GetString("BtnMergeAll2", resourceCulture);
            }
        }

        internal static string btnOutputF2
        {
            get
            {
                return ResourceManager.GetString("btnOutputF2", resourceCulture);
            }
        }

        internal static string BtnMicAudio
        {
            get
            {
                return ResourceManager.GetString("BtnMicAudio", resourceCulture);
            }
        }

        internal static string AboutForm
        {
            get
            {
                return ResourceManager.GetString("AboutForm", resourceCulture);
            }
        }

        internal static string LbAbout1
        {
            get
            {
                return ResourceManager.GetString("LbAbout1", resourceCulture);
            }
        }

        internal static string LbAbout2
        {
            get
            {
                return ResourceManager.GetString("LbAbout2", resourceCulture);
            }
        }
    }
}
