//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Screen_Recorder.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stringspt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringspt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Screen_Recorder.Langs.Stringspt", typeof(Stringspt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar audio del sistema.
        /// </summary>
        public static string BtnDeskAudio {
            get {
                return ResourceManager.GetString("BtnDeskAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar audio del sistema.
        /// </summary>
        public static string BtnDeskAudio2 {
            get {
                return ResourceManager.GetString("BtnDeskAudio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar archivos.
        /// </summary>
        public static string BtnMergeAll {
            get {
                return ResourceManager.GetString("BtnMergeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar archivos.
        /// </summary>
        public static string BtnMergeAll2 {
            get {
                return ResourceManager.GetString("BtnMergeAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar audio de microfono.
        /// </summary>
        public static string BtnMicAudio {
            get {
                return ResourceManager.GetString("BtnMicAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de salida.
        /// </summary>
        public static string btnOutputF {
            get {
                return ResourceManager.GetString("btnOutputF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpeta de salida.
        /// </summary>
        public static string btnOutputF2 {
            get {
                return ResourceManager.GetString("btnOutputF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Grabación.
        /// </summary>
        public static string btnStartRecording {
            get {
                return ResourceManager.GetString("btnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar Grabación.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar un video.
        /// </summary>
        public static string BtnVideo {
            get {
                return ResourceManager.GetString("BtnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar un video.
        /// </summary>
        public static string BtnVideo2 {
            get {
                return ResourceManager.GetString("BtnVideo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles.
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrófonos.
        /// </summary>
        public static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios del sistema (parlantes o audífonos).
        /// </summary>
        public static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes de audio.
        /// </summary>
        public static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos de sonido.
        /// </summary>
        public static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string languagesToolStripMenuItem {
            get {
                return ResourceManager.GetString("languagesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar solo un audio del sistema y video.
        /// </summary>
        public static string mergeVideoAndDesktopAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoAndDesktopAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar todos los archivos.
        /// </summary>
        public static string mergeVideoDesktopAndMicAudioToolStripMenuItem {
            get {
                return ResourceManager.GetString("mergeVideoDesktopAndMicAudioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estás grabando nada.
        /// </summary>
        public static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solamente audio del sistema.
        /// </summary>
        public static string RadioDesktop {
            get {
                return ResourceManager.GetString("RadioDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio del sistema y microfono.
        /// </summary>
        public static string RadioTwoTrack {
            get {
                return ResourceManager.GetString("RadioTwoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar archivos.
        /// </summary>
        public static string remuxToolStripMenuItem {
            get {
                return ResourceManager.GetString("remuxToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar solo video y un audio de sistema.
        /// </summary>
        public static string titleMerge1 {
            get {
                return ResourceManager.GetString("titleMerge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezclar todos los archivos.
        /// </summary>
        public static string titleMerge2 {
            get {
                return ResourceManager.GetString("titleMerge2", resourceCulture);
            }
        }
    }
}
